// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUidZk9kaiADCOeIeYAHoEKUahxky6j5Q',
    appId: '1:961900566768:web:abf5209d5f309f20edca35',
    messagingSenderId: '961900566768',
    projectId: 'esof-6405c',
    authDomain: 'esof-6405c.firebaseapp.com',
    storageBucket: 'esof-6405c.firebasestorage.app',
    measurementId: 'G-024KGYWC8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5CaXTyR32hEYRRcuWbvvkbZpmFrWXBR4',
    appId: '1:961900566768:android:a72f3d6496ec3906edca35',
    messagingSenderId: '961900566768',
    projectId: 'esof-6405c',
    storageBucket: 'esof-6405c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4FDyhU_B7tBmTCbLZmG9hIEyMVDAnQAI',
    appId: '1:961900566768:ios:7d4adf832a9bf3ccedca35',
    messagingSenderId: '961900566768',
    projectId: 'esof-6405c',
    storageBucket: 'esof-6405c.firebasestorage.app',
    iosBundleId: 'com.example.esof',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4FDyhU_B7tBmTCbLZmG9hIEyMVDAnQAI',
    appId: '1:961900566768:ios:7d4adf832a9bf3ccedca35',
    messagingSenderId: '961900566768',
    projectId: 'esof-6405c',
    storageBucket: 'esof-6405c.firebasestorage.app',
    iosBundleId: 'com.example.esof',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUidZk9kaiADCOeIeYAHoEKUahxky6j5Q',
    appId: '1:961900566768:web:9151919ae8cba4afedca35',
    messagingSenderId: '961900566768',
    projectId: 'esof-6405c',
    authDomain: 'esof-6405c.firebaseapp.com',
    storageBucket: 'esof-6405c.firebasestorage.app',
    measurementId: 'G-Z7M44VJG6K',
  );
}
